# Generated by Django 6.0.4 on 2026-05-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_livreur_user_alter_demandelivraison_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='deliveries.livreur')),
            ],
        ),
    ]
