# Generated by Django 6.0.4 on 2026-05-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='email',
        ),
    ]
