# Generated by Django 6.0.4 on 2026-05-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_remove_livreur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='vehicule',
            field=models.CharField(choices=[('velo', 'Vélo'), ('camion', 'Camion'), ('moto', 'Moto'), ('voiture', 'Voiture')], max_length=30),
        ),
    ]
