# Generated by Django 6.0.4 on 2026-05-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_alter_livreur_vehicule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_latitude', models.FloatField(blank=True, null=True)),
                ('client_longitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.client')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.livreur')),
            ],
        ),
    ]
