# Generated by Django 6.0.4 on 2026-05-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='livreurs/'),
        ),
    ]
