# Generated by Django 6.0.4 on 2026-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_livreur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairelivreur',
            name='note',
            field=models.IntegerField(default=5),
        ),
    ]
