# Generated by Django 6.0.4 on 2026-10-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0016_backfill_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='availability_before_course',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
