org.gradle.jvmargs=-Xmx768m -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=64m -XX:+HeapDumpOnOutOfMemoryError -Xss512k
org.gradle.workers.max=1
org.gradle.daemon=false
kotlin.daemon.jvm.options=-Xmx256m
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
