# Generated by Django 5.0.6 on 2026-05-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('vehicule', models.CharField(choices=[('velo', 'Vélo'), ('scooter', 'Scooter'), ('moto', 'Moto'), ('voiture', 'Voiture')], max_length=30)),
                ('disponible', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('note', models.FloatField(default=5)),
                ('nombre_livraisons', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeLivraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('client_telephone', models.CharField(max_length=30)),
                ('adresse_depart', models.CharField(max_length=255)),
                ('adresse_arrivee', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=30)),
                ('prix_estime', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tracking_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='deliveries.livreur')),
            ],
        ),
    ]
