# Generated by Django 6.0.4 on 2026-05-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_commentairelivreur_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
