# Generated by Django 6.0.4 on 2026-10-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0013_course_client_confirmed_and_nullable_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cancellation_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cancelled_by_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='destination_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='destination_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='previous_status',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='course',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('searching', 'Recherche de chauffeur'), ('driver_accepted', 'Chauffeur intéressé'), ('driver_selected', 'Chauffeur sélectionné'), ('driver_arriving', 'Chauffeur en route'), ('driver_arrived', 'Chauffeur arrivé'), ('in_progress', 'Course en cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='searching', max_length=24),
        ),
        migrations.AddField(
            model_name='course',
            name='surcharge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='deliveries.livreur'),
        ),
        migrations.CreateModel(
            name='CourseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(blank=True, max_length=16)),
                ('actor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=32)),
                ('previous_status', models.CharField(blank=True, max_length=24)),
                ('new_status', models.CharField(blank=True, max_length=24)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deliveries.course')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', 'Retirée')], default='pending', max_length=12)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='deliveries.course')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offers', to='deliveries.livreur')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'livreur'), name='unique_course_offer_per_livreur')],
            },
        ),
    ]
