# Generated by Django 6.0.4 on 2026-10-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0014_course_arrived_at_course_cancellation_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='request_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
