# Generated by Django 6.0.4 on 2026-10-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0018_course_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livreur',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
