# Generated by Django 6.0.4 on 2026-10-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0019_client_points_livreur_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='est_en_ligne',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('searching', 'Recherche de chauffeur'), ('driver_accepted', 'Chauffeur intéressé'), ('driver_selected', 'Chauffeur sélectionné'), ('driver_arriving', 'Chauffeur en route'), ('driver_arrived', 'Chauffeur arrivé'), ('picked_up', 'Commande récupérée'), ('in_progress', 'Course en cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='searching', max_length=24),
        ),
    ]
