# Generated by Django 6.0.4 on 2026-10-05 02:21

from django.db import migrations, models


def backfill_delivery_legs(apps, schema_editor):
    """Aligne les commandes existantes sur le nouveau modèle commerçant -> client.

    Avant cette migration, une commande partait de la position du client. On
    conserve ce point comme point de retrait (aucun commerçant n'était connu)
    et on reporte la distance déjà calculée sur la jambe de livraison.
    """
    Course = apps.get_model("deliveries", "Course")

    for course in Course.objects.all().iterator():
        pickup_lat = course.pickup_latitude or course.client_latitude
        pickup_lon = course.pickup_longitude or course.client_longitude
        course.pickup_latitude = pickup_lat
        course.pickup_longitude = pickup_lon
        course.pickup_distance_km = 0.0
        course.trip_distance_km = course.estimated_distance_km
        course.trip_route_geometry = course.route_geometry
        course.pickup_eta_minutes = 1
        course.save(
            update_fields=[
                "pickup_latitude",
                "pickup_longitude",
                "pickup_distance_km",
                "trip_distance_km",
                "trip_route_geometry",
                "pickup_eta_minutes",
            ]
        )


def clear_backfilled_legs(apps, schema_editor):
    """Annule le backfill (les colonnes pickup repartent vides)."""
    Course = apps.get_model("deliveries", "Course")
    Course.objects.update(
        pickup_latitude=None,
        pickup_longitude=None,
        pickup_distance_km=None,
        trip_distance_km=None,
        trip_route_geometry=None,
        pickup_eta_minutes=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0020_course_picked_up_at_courseoffer_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='broadcast_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='dropoff_eta_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='last_offer_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='pickup_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pickup_eta_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pickup_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='pickup_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='pickup_route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='trip_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='trip_route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='dropoff_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='dropoff_eta_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='pickup_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='pickup_eta_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(backfill_delivery_legs, clear_backfilled_legs),
    ]
