# Generated by Django 6.0.4 on 2026-10-08 22:02

import deliveries.private_storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0021_course_pickup_dropoff_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('license', 'Permis de conduire'), ('vehicle', 'Véhicule et plaque')], max_length=12)),
                ('file', models.FileField(storage=deliveries.private_storage.PrivateDocumentStorage(), upload_to=deliveries.private_storage.document_path)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('verified', 'تم التحقق'), ('rejected', 'مرفوض')], default='pending', max_length=12)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deliveries.livreur')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('livreur', 'kind'), name='unique_driver_document_kind')],
            },
        ),
    ]
