# Generated by Django 6.0.4 on 2026-10-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0026_client_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='deliveries.client')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_review', to='deliveries.course')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='deliveries.livreur')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
