# Generated by Django 6.0.4 on 2026-10-10 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0027_commentaireclient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_role', models.CharField(choices=[('client', 'Client'), ('livreur', 'Chauffeur')], max_length=8)),
                ('reason', models.CharField(choices=[('driver_delay', 'Retard du chauffeur'), ('driver_behavior', 'Comportement du chauffeur'), ('price', 'Prix de la course'), ('payment', 'Paiement'), ('client_absent', 'Client absent'), ('client_behavior', 'Comportement du client'), ('route', 'Trajet ou adresse'), ('other', 'Autre problème')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('in_progress', 'En cours'), ('resolved', 'Résolue')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='deliveries.course')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'reporter'), name='unique_course_complaint_per_reporter')],
            },
        ),
    ]
